spring.application.name=pet-vaccine-api

spring.datasource.url=jdbc:mysql://localhost:3307/pet_vaccine_db
spring.datasource.username=root
spring.datasource.password=2323

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true